// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTGXtPeJfBngqkysJTpFwTdVfqc7-zrfg',
    appId: '1:477024448533:web:5f932a6435db4bcf5dde1c',
    messagingSenderId: '477024448533',
    projectId: 'to-do-list-f9677',
    authDomain: 'to-do-list-f9677.firebaseapp.com',
    storageBucket: 'to-do-list-f9677.appspot.com',
    measurementId: 'G-58K1V0RMD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0bbyylnhnRPWtaY6z1Gy3wyf3Bx0ma8',
    appId: '1:477024448533:android:d341c1a4e5af6e855dde1c',
    messagingSenderId: '477024448533',
    projectId: 'to-do-list-f9677',
    storageBucket: 'to-do-list-f9677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAveXWe6yKWrj5wsx_AkNAxnEVw2eDIWbc',
    appId: '1:477024448533:ios:b4af5e27e24248e95dde1c',
    messagingSenderId: '477024448533',
    projectId: 'to-do-list-f9677',
    storageBucket: 'to-do-list-f9677.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAveXWe6yKWrj5wsx_AkNAxnEVw2eDIWbc',
    appId: '1:477024448533:ios:4acfe8ceb28828605dde1c',
    messagingSenderId: '477024448533',
    projectId: 'to-do-list-f9677',
    storageBucket: 'to-do-list-f9677.appspot.com',
    iosBundleId: 'com.example.baseTodolist.RunnerTests',
  );
}
